services:
  - type: web
    name: art-education-app
    env: python
    buildCommand: |
      python -m venv .venv
      . .venv/bin/activate
      pip install -r requirements.txt
      python -m spacy download en_core_web_lg
    startCommand: |
      . .venv/bin/activate
      /opt/render/.local/bin/gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PORT
        value: 10000
      - key: MET_API_KEY
        value: not_required
      - key: AIC_API_KEY
        value: not_required
    healthCheckPath: /
    autoDeploy: true
