services:
  - type: web
    name: art-education-app
    env: python
    buildCommand: |
      python -m venv .venv
      . .venv/bin/activate
      pip install --upgrade pip
      pip install wheel
      pip install gunicorn==21.2.0
      pip install -r requirements.txt
      python -m spacy download en_core_web_lg
    startCommand: |
      . .venv/bin/activate
      export PYTHONPATH="${PYTHONPATH}:${PWD}"
      export PATH="/opt/render/project/.venv/bin:$PATH"
      which gunicorn
      gunicorn app:app --bind=0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PORT
        value: 10000
      - key: MET_API_KEY
        value: not_required
      - key: AIC_API_KEY
        value: not_required
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /
    autoDeploy: true
