services:
  - type: web
    name: metis
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11.10
    buildCommand: |
      python -m venv .venv
      . .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      pip install gunicorn
    startCommand: |
      . .venv/bin/activate
      gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHON_VERSION
        value: 3.11.10
