services:
  - type: web
    name: metis
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11.10
    buildCommand: |
      python -m venv .venv
      source .venv/bin/activate
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
      python -m pip install gunicorn
      python -m spacy download en_core_web_sm
    startCommand: |
      source .venv/bin/activate
      export PYTHONPATH=/opt/render/project/src
      gunicorn --bind 0.0.0.0:$PORT app:app --log-level debug
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PORT
        value: 10000
