services:
  - type: web
    name: metis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GUNICORN_CMD_ARGS
        value: "--log-level debug --timeout 120"
