services:
  - type: web
    name: metis-art-education
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11.10
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_lg
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
