services:
  - type: web
    name: metis-art-education
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11.10
    buildCommand: |
      python -m venv .venv
      . .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_lg
      pip install gunicorn
    startCommand: |
      export VIRTUAL_ENV=/opt/render/project/src/.venv
      . .venv/bin/activate
      chmod +x start.sh
      ./start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONPATH
        value: /opt/render/project/src
